logs:
    - name: root
      level: info
      formatter: "%d%T%m%n"
      appender:
        - type: FileLogAppender
          file: log.txt
        - type: StdOutLogAppender
    - name: system
      level: debug
      formatter: "%d%T%m%n"
      appender:
        - type: FileLogAppender
          path: log.txt
        - type: StdOutLogAppender

system:
  int: 9900
  float: 20
  int_vec: [10,30]
  int_list: [100,200]
  int_set: [111,222]
  int_unordered_set: [111,222]
  string_int_map: 
    k1: 10 
    k2: 20 
    k3: 30 
  string_int_unordered_map: 
    k1: 10 
    k2: 20 
    k3: 30

class:
  person: 
    name: zhangyanzhou
    age: 20
    sex: 男
  map: 
    zyz1: 
      name: zyz1
      age: 20
      sex: 男
    zyz2:
      name: zyz2
      age: 30
      sex: 女
  vec_map:
    k1: 
      - name: name1
        age: 22
        sex: 男
      - name: name2
        age: 30
        sex: 女
    k2: 
      - name: name3
        age: 33
        sex: 男
      - name: name4
        age: 24
        sex: 女
  